# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5ae377e679d459a70cf9ea8ba978b850c2e373c4924e9186889452990b96974accb83e170b84a8951bf2127a5c8bd9c0175e19956dc8815c6941f6560018d5e9

test:
  secret_key_base: 09b7741063929d5290be6e4e6f13973e1e667369199028fa9debe049e10dd6d33b89c87735b1f0e2f27456d6f64e43d0a3fdcfe88499e7789a3511c5f55874cd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
